mojo: Fix optional bools
We were generating the following code for optional bools:

```
absl::make_optional(data_->optional_bool_$value)
```

Which failed to compile because `optional_bool_$value` is a bit-field:
```
error: non-const reference cannot bind to bit-field 'b_value_$value'
```

This CL fixes the generator to output:
```
absl::make_optional(!!data_->optional_bool_$value)
```

Also adds tests for optional bools.

Bug: 657632
Change-Id: Ifd158acb0629c1c78d808fc4692f621fcb990de4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4316445
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Commit-Queue: Giovanni Ortuno Urquidi <ortuno@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1114868}


CrOS-Libchrome-Original-Commit: 2099148d8602e0c5a772768caa660c142a8d6136