[base] Properly detect NEON support on ARM{,64}
olivierli@chromium.org discovered that CPU_ARM_NEON is not defined where
it should (in particular on ARM64). This commit fixes the detection.

However, fixing this makes ARM64 builds fail. This is because of buggy
hand-written assembly code in WTF::CopyLCharsFramUCharSource() for the
NEON path. The path uses inline assembly to perform the char16_t -> char
conversion in the case where all the characters in the char16_t array
are 8-bit. This is potentially quite hot code in blink, but the code is
broken because it uses inline assembly with incorrect registers.

A clean solution would be to use intrinsics, but a lazier one is to
trust the "sufficiently smart compiler", which indeed auto-vectorizes
the loop at "-O2" (tested with compiler explorer, on reasonably recent
clang versions). Since this assembly code path wasn't used before, we
lose nothing by not using inline assembly.

For reference, the error message generated when leaving the inline
assembly as is:

In file included from ../../third_party/blink/renderer/platform/wtf/text/wtf_string.cc:41:
../../third_party/blink/renderer/platform/wtf/text/copy_lchars_from_uchar_source.h:97:11: error: vector register expected
      asm("vld2.8   { d0-d1 }, [%[SOURCE]] !\n\t"
          ^
<inline asm>:1:13: note: instantiated into assembly here
        vld2.8   { d0-d1 }, [x1] !

Also need to update a webaudio fingerprinting test. The result changes
because... floating point, and enabling NEON expectedly changes the
results.

Note for sheriffs: If there is a build breakage on ARM64 in range, this is likely the culprit.

Change-Id: I1b81babc0823dbd53aa2ce263c3f2fa2427e29c9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4579589
Reviewed-by: Francois Pierre Doray <fdoray@chromium.org>
Commit-Queue: Benoit Lize <lizeb@chromium.org>
Reviewed-by: Hongchan Choi <hongchan@chromium.org>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1153278}


CrOS-Libchrome-Original-Commit: 59edf62cfd5c0ec43dcb5d3d7358c5c314208f2e