win: Add missing <limits> include
Fixes the following error when building on Windows with
`use_custom_libcxx=false`:

oom.cc(52,36): error: no member named 'numeric_limits' in namespace 'std'
   52 |   constexpr size_t kInvalid = std::numeric_limits<ULONG_PTR>::max();
      |                               ~~~~~^

Change-Id: I78f1c3fcadac649dcd4f32d0620ba4c6a06bac88
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5891459
Commit-Queue: Marshall Greenblatt <marshall@chromium.org>
Reviewed-by: Francois Pierre Doray <fdoray@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1360693}


CrOS-Libchrome-Original-Commit: feaf861dd823caecbf4e2301deb07fd3ee342c9e