ifdef-out IsRunning32bitEmulatedOnArm64 in non PA-E builds
This function is only used from some code behind a similar ifdef, so it
results in some unused function warnings if we don't also ifdef this
function.

See https://ci.chromium.org/ui/p/chrome/builders/official/win-clang/2092/overview
for an example of how this fails:
../../base/allocator/allocator_shim_default_dispatch_to_partition_alloc.cc(120,6): error: unused function 'IsRunning32bitEmulatedOnArm64' [-Werror,-Wunused-function]
bool IsRunning32bitEmulatedOnArm64() {
^

Bug: 1121427
Change-Id: I14ff07fce431fd4aa52fd197c59d70df0237ad20
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2615327
Reviewed-by: Will Harris <wfh@chromium.org>
Commit-Queue: Sébastien Marchand <sebmarchand@chromium.org>
Cr-Commit-Position: refs/heads/master@{#841260}


CrOS-Libchrome-Recovered-From-Commit: 5f97981e16b911da5b9e79e77ab2537b57cd627c