Revert "Move task-related files from base/ to base/task/"
This reverts commit 092c30c5fd4def5a0c63d6f3a8953bd07768dd44.

Reason for revert: Breaks internal builds (mac, chromeos), example:
https://ci.chromium.org/ui/p/chrome/builders/ci/mac-chrome/18730/overview

fatal error: 'base/sequenced_task_runner.h' file not found
#include "base/sequenced_task_runner.h"

Original change's description:
> Move task-related files from base/ to base/task/
>
> The forward headers are updated to point to the new location, and the
> header guards were fixed.
>
> Bug: 1255932
> Change-Id: Id84a0dd71720efee6d222a0fc0a89c1de8c1d72c
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3214950
> Commit-Queue: Gabriel Charette <gab@chromium.org>
> Reviewed-by: Gabriel Charette <gab@chromium.org>
> Owners-Override: Gabriel Charette <gab@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#930627}

Bug: 1255932
Change-Id: I79d4ded2d5d93e4b7388e0de69dbd296d818e8e1
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3219382
Auto-Submit: James Cook <jamescook@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: François Doray <fdoray@chromium.org>
Owners-Override: François Doray <fdoray@chromium.org>
Cr-Commit-Position: refs/heads/main@{#930667}


CrOS-Libchrome-Original-Commit: dc806e80f666530fcec7cf0068fb4090d7cd988e