Properly escape paths in mojom_parser_unittest.py
Previously we were generating json containing paths by directly
including the paths as strings. This caused the tests to fail on
Windows:

json.decoder.JSONDecodeError: Invalid \escape: line 1 column 34 (char 33)

Now we build the json properly with json.dumps, and the tests now
pass on Windows.

Bug: 931315
Tests: vpython3 mojo/public/tools/run_all_python_unittests.py
Change-Id: Id38dbae31eda07cd072b0ead29c7a7e1f2e78f19
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3572927
Reviewed-by: Robert Sesek <rsesek@chromium.org>
Commit-Queue: Alex Gough <ajgo@chromium.org>
Cr-Commit-Position: refs/heads/main@{#989188}


CrOS-Libchrome-Original-Commit: 3b7c8370fdf9af2fa6458fbaf7debd8dc1e124ee