Improve error message for batched tests cascading failures
For failures after the first failure in a batch, the thrown exception is
wrapped with a CascadingFailureException to explain that the current
failure could be caused by the first failure.

Error message now looks like:
```
[FAILURE] org.chromium.chrome.browser.toolbar.top.TabSwitcherActionMenuBatchedPTTest#testOpenNewIncognitoTab:
  CascadingFailureException: A previous batched test (testClosingAllRegularTabs_DoNotFinishActivity) failed and may be the cause of the current failure. See suppressed failure below.
  	at org.chromium.base.test.BaseJUnit4ClassRunner.wrapExceptionIfCascadingFailure(BaseJUnit4ClassRunner.java:409)
  	at org.chromium.base.test.BaseJUnit4ClassRunner.-$$Nest$mwrapExceptionIfCascadingFailure(Unknown Source:0)
  	at org.chromium.base.test.BaseJUnit4ClassRunner$3.evaluate(BaseJUnit4ClassRunner.java:393)
  	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
    ...
  	Suppressed: java.lang.AssertionError: expected:<1> but was:<2>
  		at org.junit.Assert.fail(Assert.java:89)
  		at org.junit.Assert.failNotEquals(Assert.java:835)
  		at org.junit.Assert.assertEquals(Assert.java:647)
  		at org.junit.Assert.assertEquals(Assert.java:633)
  		at org.chromium.chrome.browser.toolbar.top.TabSwitcherActionMenuBatchedPTTest.testOpenNewIncognitoTab(TabSwitcherActionMenuBatchedPTTest.java:103)
  		...
```

Bug: 330927824
Change-Id: Ic9aa5841097a11a626f729b0407706d02e45d0ac
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5633349
Reviewed-by: Henrique Nakashima <hnakashima@chromium.org>
Commit-Queue: Mohamed Heikal <mheikal@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1316734}


CrOS-Libchrome-Original-Commit: ee691865d7b82d4c23dd68fc8b47b981eed4efeb