Fix allocator_shim warnings with -pedantic
When using partition_alloc in dawn with "-pedantic", it fails because of
two warnings. This patch fixes/ignore the warning.

Error 1:
```
[...]/partition_ref_count.h:358:46: error: empty expression statement
has no effect; remove unnecessary ';' to silence this warning
[-Werror,-Wextra-semi-stmt]

PA_DEBUG_DATA_ON_STACK("refcount", count);
```

Error 2:
```
[...]/partition_page.h:333:15: error: offset of on non-standard-layout
type 'PartitionPage' [-Werror,-Winvalid-offsetof]

static_assert(offsetof(PartitionPage, subsequent_page_metadata) == 0, "");
```

Bug: chromium:1464560
Change-Id: I02a2454094670b2e55d0b9b92b8ae0506e8c7150
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5014269
Commit-Queue: Arthur Sonzogni <arthursonzogni@chromium.org>
Reviewed-by: danakj <danakj@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1222289}


CrOS-Libchrome-Original-Commit: bb3ef13651bee98ee873a12fbec7a0751dc4b973