Improve Mojo error messages for nullable types
If you define a Mojo struct including:

  mojo_base.mojom.Time? time;

but forget to import time.mojom, you currently get the inscrutable error
message:

  AttributeError: 'Kind' object has no attribute 'MakeNullableKind'

Even worse, because we parse transitive includes, we can't even look at
the current build command to know where the error is. This CL improves
the error message to:

  Exception: Unknown spec: ?x:mojo_base.mojom.Time. Check for missing imports in your/mojom/file.mojom

Change-Id: I545776e87047d80d9c5898157bfdac6d50b741d4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6032992
Reviewed-by: Alex Gough <ajgo@chromium.org>
Commit-Queue: Daniel Rubery <drubery@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1384690}


CrOS-Libchrome-Original-Commit: c62243afa9c5448dd0168d270846eb4b70f859b6