Revert "Re-enable Abseil flags support in GoogleTest."
This reverts commit aa3936064e4896c948b8e82351a47b5d107fc6fe.

Reason for revert: suspect causing tests failures on Linux Tests (Dbg)(1).
- content_unittests failed.
- browser_tests failed.
- device_unittests failed.

First build failure:
https://ci.chromium.org/ui/p/chromium/builders/ci/Linux%20Tests%20(dbg)(1)/119054/overview

Sample log:
ERROR: Flag 'gmock_catch_leaked_mocks' was defined more than once but with differing types. Defined in files '../../third_party/googletest/src/googlemock/src/gmock.cc' and '../../third_party/googletest/src/googlemock/src/gmock.cc'.

Original change's description:
> Re-enable Abseil flags support in GoogleTest.
>
> While Abseil now supports a GTEST_NO_ABSL_FLAGS define, and Chrome could
> simply set that define (once the corresponding GoogleTest version is
> rolled in), there are other third-party test projects that need to use
> parts of Abseil not normally allowed in Chrome, e.g.  fuzztest's
> Centipede. This serves as a proof-of-concept to validate the overall
> approach.
>
> Bug: 326607005
> Bug: 40286621
> Change-Id: I982c8f7eaca1d20dd0d057fd2035db5cd271b99c
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5321837
> Reviewed-by: Nico Weber <thakis@chromium.org>
> Commit-Queue: Daniel Cheng <dcheng@chromium.org>
> Reviewed-by: Mirko Bonadei <mbonadei@chromium.org>
> Reviewed-by: Sorin Jianu <sorin@chromium.org>
> Reviewed-by: Danil Chapovalov <danilchap@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1268129}

Bug: 326607005
Bug: 40286621
Change-Id: Ie5ed81138b3a751f9923dcc000793f87f6ab9efa
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5340276
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/main@{#1268228}


CrOS-Libchrome-Original-Commit: e0195dcd02deb75df4bfd994a224df47f67f3ff6