[install-build-deps] Remove print output in check_call exception
If some packages install failed (caused by some package do not exists
or network issue, etc.), there no output attribute in the check_call
raised error, we will get error message show like this:
AttributeError: 'NoneType' object has no attribute 'decode'.
This change removed print output in exception error to fix this.

Bug: 362427426
Bug: 356905949
Change-Id: I415a71cb118c901c486251826b6c9a1ce666eaec
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5828084
Commit-Queue: Lei Zhang <thestig@chromium.org>
Reviewed-by: Thomas Anderson <thomasanderson@chromium.org>
Reviewed-by: Lei Zhang <thestig@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1349579}


CrOS-Libchrome-Original-Commit: cfb58be2715dc3d5a39ff715ee03db5c61b571a2