Android Instrumentation Tests: Prevent loading classes with higher @MinAndroidSdkLevel
Doing so can cause NoClassDefFoundError to be thrown by junit when
listing methods (if methods contain types from higher sdk version).
E.g.: https://chromium-review.googlesource.com/c/chromium/src/+/4738415/1

Bug: None
Change-Id: I9181763d3817e1424fa2758ec528fc62b444ca03
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4742348
Commit-Queue: Sam Maier <smaier@chromium.org>
Auto-Submit: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Reviewed-by: Sam Maier <smaier@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1178469}


CrOS-Libchrome-Original-Commit: 58ef59246312f8934e3b6702a51f69ad36e0270d