PA: Fix (potentially) compile errors with MSVC.
I suspect the problem is that `ContainsFlags` template being defined in
`partition_alloc::internal`, but used from `base::raw_ptr_traits`.

According to Dana & Mikihito, this should compile thanks to ADL
lookup.
If this patch doesn't resolve the issue, I will revert it.

Please note that I am currently not in the capacity to reproduce locally
the MSVC error:
https://ci.chromium.org/ui/p/dawn/builders/try/win-msvc-dbg-x64/b8764895406724734097/overview
```
C:\b\s\w\ir\cache\builder\dawn\third_party\partition_alloc\src\partition_alloc/pointers/raw_ptr.h(266): error C2975: '_Test': invalid template argument for 'std::conditional_t', expected compile-time constant expression
C:\b\s\w\ir\cache\win_toolchain\vs_files\27370823e7\VC\Tools\MSVC\14.34.31933\include\xtr1common(63): note: see declaration of '_Test'
```

Bug: 1501832
Change-Id: I9797edfbe4906bf501dadbc3cda12a10e0da7e48
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5024258
Reviewed-by: danakj <danakj@chromium.org>
Reviewed-by: Mikihito Matsuura <mikt@google.com>
Commit-Queue: Arthur Sonzogni <arthursonzogni@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1223725}


CrOS-Libchrome-Original-Commit: cc273d730824948cec5f7551c648d61278c4048a