GCC: add move constructor to base::Location
GCC requires a noexcept move constructor in base::Location,
because internal::PostedTask move constructor is noexcept.
Otherwise it fails with:
../../base/task/sequence_manager/tasks.cc:80:1: error: function
 '...' defaulted on its redeclaration with an exception-specification
 that differs from the implicit exception-specification ''
   80 | PostedTask::PostedTask(PostedTask&& move_from) noexcept = default;
      | ^~~~~~~~~~

Bug: 819294
Change-Id: Icd01e7adb2c7173aa324ff5f427cd8ae92771e7a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3314831
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Commit-Queue: Stephan Hartmann <stha09@googlemail.com>
Cr-Commit-Position: refs/heads/main@{#949250}


CrOS-Libchrome-Original-Commit: 66f224a54a2e063c48010c4b18fa176a6c22547c